In [1]:
import os
os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"] = ".13"

In [12]:
import pandas as pd
from brain import BrainModel
from submodels import factories
import matplotlib.pyplot as plt
import pandas as pd
from itertools import accumulate
import numpy as np
from collections import defaultdict
import re

from lib.sde.grn.grn4 import GRNMain4
from lib.sde.mutate import mutate_grn3
from lib.ga.utils import weighted_selection
from lib.ga.objective import Objective
from jf.profiler import Profiler
from jf.utils.export import Exporter
from jf.autocompute.jf import O, L

In [3]:
class Solution:
    def __init__(self, grn):
        self.grn = grn
        
    def copy(self):
        return Solution(self.grn.copy())
        
    def mutate(self):
        mutate_grn2(self.grn)

In [4]:
def get_bb(grn):
    ccls = factories["grn4"](grn=grn)
    bb = BrainModel(time_step=0.5, verbose=False, start_population=5, max_pop_size=1e3, opti=True, 
            cell_cls=ccls, end_time=55, start_time=50, silent=True, record_population=True)
    return bb

In [5]:
def run_grn(prun, grn):
    get_bb(prun, grn)
    bb.run()
    return bb

In [6]:
while True:
    print("x", end="")
    grn = GRNMain4(nb_genes=5, nb_membrane_gene=1, nb_off_trees=0)
    grn

    bb = get_bb(grn)

    bb.run()

    if len(bb.snapshots) > 4:
        break

xx

In [7]:
[len(x["population"]) for x in bb.snapshots.values()][:10]

[22, 16, 17, 13, 14, 12]

In [8]:
np.array(list(bb.snapshots[50.5]["population"].values()))[:5]

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.3111496 , 0.22796056, 0.        , 0.        , 0.06982006],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.06288064, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.0958944 , 0.        ]],
      dtype=float32)

In [9]:
np.array(list(bb.snapshots[51.0]["population"].values()))[:5]

array([[0.45884708, 0.47314435, 0.01437277, 0.17205116, 0.03953689],
       [0.2531733 , 0.03064433, 0.01437277, 0.1737388 , 0.02602543],
       [0.45884708, 0.47314435, 0.01437277, 0.17205116, 0.03953689],
       [0.22244033, 0.47403574, 0.01437277, 0.17240657, 0.03953689],
       [0.45884708, 0.47373804, 0.01645037, 0.23651865, 0.04525197]],
      dtype=float32)

In [13]:
L(bb.population.base_population.values()).cell_program.environment

[DeviceArray([0.9994332], dtype=float32),
 DeviceArray([1.9988567], dtype=float32),
 DeviceArray([1.9988655], dtype=float32),
 DeviceArray([1.9988637], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([5.996623], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([3.9977176], dtype=float32),
 DeviceArray([0.9994277], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([0.], dtype=float32),
 DeviceArray([2.998326], dtype=float32),
 DeviceArray([1.999761], dtype=float32),
 DeviceArray([2.9996262], dtyp